//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOperacion
    {
        public int IdRolOperacion { get; set; }
        public int IdRol { get; set; }
        public int IdOperacion { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
