//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvCategoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvCategoria.IsrvCategoria")]
    public interface IsrvCategoria {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/recCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/recCategoria_ENTResponse")]
        System.Collections.Generic.List<Entidades.Categoria> recCategoria_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/recCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/recCategoria_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Categoria>> recCategoria_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/recCategoriaXId_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/recCategoriaXId_ENTResponse")]
        Entidades.Categoria recCategoriaXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/recCategoriaXId_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/recCategoriaXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Categoria> recCategoriaXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/insCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/insCategoria_ENTResponse")]
        bool insCategoria_ENT(Entidades.Categoria pCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/insCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/insCategoria_ENTResponse")]
        System.Threading.Tasks.Task<bool> insCategoria_ENTAsync(Entidades.Categoria pCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/modCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/modCategoria_ENTResponse")]
        bool modCategoria_ENT(Entidades.Categoria pCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/modCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/modCategoria_ENTResponse")]
        System.Threading.Tasks.Task<bool> modCategoria_ENTAsync(Entidades.Categoria pCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/delCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/delCategoria_ENTResponse")]
        bool delCategoria_ENT(Entidades.Categoria pCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCategoria/delCategoria_ENT", ReplyAction="http://tempuri.org/IsrvCategoria/delCategoria_ENTResponse")]
        System.Threading.Tasks.Task<bool> delCategoria_ENTAsync(Entidades.Categoria pCategoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvCategoriaChannel : mvcInterfazUsuario.srvCategoria.IsrvCategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvCategoriaClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvCategoria.IsrvCategoria>, mvcInterfazUsuario.srvCategoria.IsrvCategoria {
        
        public IsrvCategoriaClient() {
        }
        
        public IsrvCategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvCategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Categoria> recCategoria_ENT() {
            return base.Channel.recCategoria_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Categoria>> recCategoria_ENTAsync() {
            return base.Channel.recCategoria_ENTAsync();
        }
        
        public Entidades.Categoria recCategoriaXId_ENT(int pId) {
            return base.Channel.recCategoriaXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Categoria> recCategoriaXId_ENTAsync(int pId) {
            return base.Channel.recCategoriaXId_ENTAsync(pId);
        }
        
        public bool insCategoria_ENT(Entidades.Categoria pCategoria) {
            return base.Channel.insCategoria_ENT(pCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> insCategoria_ENTAsync(Entidades.Categoria pCategoria) {
            return base.Channel.insCategoria_ENTAsync(pCategoria);
        }
        
        public bool modCategoria_ENT(Entidades.Categoria pCategoria) {
            return base.Channel.modCategoria_ENT(pCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> modCategoria_ENTAsync(Entidades.Categoria pCategoria) {
            return base.Channel.modCategoria_ENTAsync(pCategoria);
        }
        
        public bool delCategoria_ENT(Entidades.Categoria pCategoria) {
            return base.Channel.delCategoria_ENT(pCategoria);
        }
        
        public System.Threading.Tasks.Task<bool> delCategoria_ENTAsync(Entidades.Categoria pCategoria) {
            return base.Channel.delCategoria_ENTAsync(pCategoria);
        }
    }
}
