//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EnhancerForBusiness_Web.Models.Context
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EnhancerForBusinessModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EnhancerForBusinessModelContainer object using the connection string found in the 'EnhancerForBusinessModelContainer' section of the application configuration file.
        /// </summary>
        public EnhancerForBusinessModelContainer() : base("name=EnhancerForBusinessModelContainer", "EnhancerForBusinessModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EnhancerForBusinessModelContainer object.
        /// </summary>
        public EnhancerForBusinessModelContainer(string connectionString) : base(connectionString, "EnhancerForBusinessModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EnhancerForBusinessModelContainer object.
        /// </summary>
        public EnhancerForBusinessModelContainer(EntityConnection connection) : base(connection, "EnhancerForBusinessModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
