//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvCliente.IsrvCliente")]
    public interface IsrvCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/recCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/recCliente_ENTResponse")]
        System.Collections.Generic.List<Entidades.Cliente> recCliente_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/recCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/recCliente_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Cliente>> recCliente_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/recClienteXId_ENT", ReplyAction="http://tempuri.org/IsrvCliente/recClienteXId_ENTResponse")]
        Entidades.Cliente recClienteXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/recClienteXId_ENT", ReplyAction="http://tempuri.org/IsrvCliente/recClienteXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Cliente> recClienteXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/insCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/insCliente_ENTResponse")]
        bool insCliente_ENT(Entidades.Cliente pCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/insCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/insCliente_ENTResponse")]
        System.Threading.Tasks.Task<bool> insCliente_ENTAsync(Entidades.Cliente pCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/modCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/modCliente_ENTResponse")]
        bool modCliente_ENT(Entidades.Cliente pCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/modCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/modCliente_ENTResponse")]
        System.Threading.Tasks.Task<bool> modCliente_ENTAsync(Entidades.Cliente pCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/delCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/delCliente_ENTResponse")]
        bool delCliente_ENT(Entidades.Cliente pCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCliente/delCliente_ENT", ReplyAction="http://tempuri.org/IsrvCliente/delCliente_ENTResponse")]
        System.Threading.Tasks.Task<bool> delCliente_ENTAsync(Entidades.Cliente pCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvClienteChannel : mvcInterfazUsuario.srvCliente.IsrvCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvClienteClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvCliente.IsrvCliente>, mvcInterfazUsuario.srvCliente.IsrvCliente {
        
        public IsrvClienteClient() {
        }
        
        public IsrvClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Cliente> recCliente_ENT() {
            return base.Channel.recCliente_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Cliente>> recCliente_ENTAsync() {
            return base.Channel.recCliente_ENTAsync();
        }
        
        public Entidades.Cliente recClienteXId_ENT(int pId) {
            return base.Channel.recClienteXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Cliente> recClienteXId_ENTAsync(int pId) {
            return base.Channel.recClienteXId_ENTAsync(pId);
        }
        
        public bool insCliente_ENT(Entidades.Cliente pCliente) {
            return base.Channel.insCliente_ENT(pCliente);
        }
        
        public System.Threading.Tasks.Task<bool> insCliente_ENTAsync(Entidades.Cliente pCliente) {
            return base.Channel.insCliente_ENTAsync(pCliente);
        }
        
        public bool modCliente_ENT(Entidades.Cliente pCliente) {
            return base.Channel.modCliente_ENT(pCliente);
        }
        
        public System.Threading.Tasks.Task<bool> modCliente_ENTAsync(Entidades.Cliente pCliente) {
            return base.Channel.modCliente_ENTAsync(pCliente);
        }
        
        public bool delCliente_ENT(Entidades.Cliente pCliente) {
            return base.Channel.delCliente_ENT(pCliente);
        }
        
        public System.Threading.Tasks.Task<bool> delCliente_ENTAsync(Entidades.Cliente pCliente) {
            return base.Channel.delCliente_ENTAsync(pCliente);
        }
    }
}
