//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvVenta.IsrvVenta")]
    public interface IsrvVenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/recVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/recVenta_ENTResponse")]
        System.Collections.Generic.List<Entidades.Venta> recVenta_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/recVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/recVenta_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Venta>> recVenta_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/recVentaXId_ENT", ReplyAction="http://tempuri.org/IsrvVenta/recVentaXId_ENTResponse")]
        Entidades.Venta recVentaXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/recVentaXId_ENT", ReplyAction="http://tempuri.org/IsrvVenta/recVentaXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Venta> recVentaXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/insVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/insVenta_ENTResponse")]
        bool insVenta_ENT(Entidades.Venta pVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/insVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/insVenta_ENTResponse")]
        System.Threading.Tasks.Task<bool> insVenta_ENTAsync(Entidades.Venta pVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/modVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/modVenta_ENTResponse")]
        bool modVenta_ENT(Entidades.Venta pVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/modVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/modVenta_ENTResponse")]
        System.Threading.Tasks.Task<bool> modVenta_ENTAsync(Entidades.Venta pVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/delVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/delVenta_ENTResponse")]
        bool delVenta_ENT(Entidades.Venta pVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvVenta/delVenta_ENT", ReplyAction="http://tempuri.org/IsrvVenta/delVenta_ENTResponse")]
        System.Threading.Tasks.Task<bool> delVenta_ENTAsync(Entidades.Venta pVenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvVentaChannel : mvcInterfazUsuario.srvVenta.IsrvVenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvVentaClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvVenta.IsrvVenta>, mvcInterfazUsuario.srvVenta.IsrvVenta {
        
        public IsrvVentaClient() {
        }
        
        public IsrvVentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvVentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvVentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvVentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Venta> recVenta_ENT() {
            return base.Channel.recVenta_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Venta>> recVenta_ENTAsync() {
            return base.Channel.recVenta_ENTAsync();
        }
        
        public Entidades.Venta recVentaXId_ENT(int pId) {
            return base.Channel.recVentaXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Venta> recVentaXId_ENTAsync(int pId) {
            return base.Channel.recVentaXId_ENTAsync(pId);
        }
        
        public bool insVenta_ENT(Entidades.Venta pVenta) {
            return base.Channel.insVenta_ENT(pVenta);
        }
        
        public System.Threading.Tasks.Task<bool> insVenta_ENTAsync(Entidades.Venta pVenta) {
            return base.Channel.insVenta_ENTAsync(pVenta);
        }
        
        public bool modVenta_ENT(Entidades.Venta pVenta) {
            return base.Channel.modVenta_ENT(pVenta);
        }
        
        public System.Threading.Tasks.Task<bool> modVenta_ENTAsync(Entidades.Venta pVenta) {
            return base.Channel.modVenta_ENTAsync(pVenta);
        }
        
        public bool delVenta_ENT(Entidades.Venta pVenta) {
            return base.Channel.delVenta_ENT(pVenta);
        }
        
        public System.Threading.Tasks.Task<bool> delVenta_ENTAsync(Entidades.Venta pVenta) {
            return base.Channel.delVenta_ENTAsync(pVenta);
        }
    }
}
