//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcInterfazUsuario.srvCompra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvCompra.IsrvCompra")]
    public interface IsrvCompra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/recCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/recCompra_ENTResponse")]
        System.Collections.Generic.List<Entidades.Compra> recCompra_ENT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/recCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/recCompra_ENTResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Compra>> recCompra_ENTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/recCompraXId_ENT", ReplyAction="http://tempuri.org/IsrvCompra/recCompraXId_ENTResponse")]
        Entidades.Compra recCompraXId_ENT(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/recCompraXId_ENT", ReplyAction="http://tempuri.org/IsrvCompra/recCompraXId_ENTResponse")]
        System.Threading.Tasks.Task<Entidades.Compra> recCompraXId_ENTAsync(int pId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/insCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/insCompra_ENTResponse")]
        bool insCompra_ENT(Entidades.Compra pCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/insCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/insCompra_ENTResponse")]
        System.Threading.Tasks.Task<bool> insCompra_ENTAsync(Entidades.Compra pCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/modCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/modCompra_ENTResponse")]
        bool modCompra_ENT(Entidades.Compra pCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/modCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/modCompra_ENTResponse")]
        System.Threading.Tasks.Task<bool> modCompra_ENTAsync(Entidades.Compra pCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/delCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/delCompra_ENTResponse")]
        bool delCompra_ENT(Entidades.Compra pCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvCompra/delCompra_ENT", ReplyAction="http://tempuri.org/IsrvCompra/delCompra_ENTResponse")]
        System.Threading.Tasks.Task<bool> delCompra_ENTAsync(Entidades.Compra pCompra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvCompraChannel : mvcInterfazUsuario.srvCompra.IsrvCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvCompraClient : System.ServiceModel.ClientBase<mvcInterfazUsuario.srvCompra.IsrvCompra>, mvcInterfazUsuario.srvCompra.IsrvCompra {
        
        public IsrvCompraClient() {
        }
        
        public IsrvCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.Compra> recCompra_ENT() {
            return base.Channel.recCompra_ENT();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Compra>> recCompra_ENTAsync() {
            return base.Channel.recCompra_ENTAsync();
        }
        
        public Entidades.Compra recCompraXId_ENT(int pId) {
            return base.Channel.recCompraXId_ENT(pId);
        }
        
        public System.Threading.Tasks.Task<Entidades.Compra> recCompraXId_ENTAsync(int pId) {
            return base.Channel.recCompraXId_ENTAsync(pId);
        }
        
        public bool insCompra_ENT(Entidades.Compra pCompra) {
            return base.Channel.insCompra_ENT(pCompra);
        }
        
        public System.Threading.Tasks.Task<bool> insCompra_ENTAsync(Entidades.Compra pCompra) {
            return base.Channel.insCompra_ENTAsync(pCompra);
        }
        
        public bool modCompra_ENT(Entidades.Compra pCompra) {
            return base.Channel.modCompra_ENT(pCompra);
        }
        
        public System.Threading.Tasks.Task<bool> modCompra_ENTAsync(Entidades.Compra pCompra) {
            return base.Channel.modCompra_ENTAsync(pCompra);
        }
        
        public bool delCompra_ENT(Entidades.Compra pCompra) {
            return base.Channel.delCompra_ENT(pCompra);
        }
        
        public System.Threading.Tasks.Task<bool> delCompra_ENTAsync(Entidades.Compra pCompra) {
            return base.Channel.delCompra_ENTAsync(pCompra);
        }
    }
}
